### ISSUE TITLE
企业微信的自建应用可以直接给微信号推送消息

### ISSUE THREAD

**Issue by wangyunpengbio** [songquanpeng/message-pusher#10]
我看了企业微信的应用的消息推送api，https://work.weixin.qq.com/api/doc/90000/90135/90235
该api是可以直接通过企业微信后台发送请求，进而通过企业微信应用给微信号推送消息的。所以这个项目是把该api包了一层，变成向自己的服务器发送请求，接着自己的服务器向企业微信后台发送请求，是这样吗？

**Comment by songquanpeng** [comment]
对的，主要是 token 的保存与刷新，并且把其他的消息发送方式用一个统一的方便调用的 api 封装起来了

**Comment by wangyunpengbio** [comment]
哦哦，原来是这样。理解啦

**Comment by songquanpeng** [comment]
那就先把 issue 关了哈，有问题再开。
