### ISSUE TITLE
增加PushMe推送通道

### ISSUE THREAD

**Issue by yafoo** [songquanpeng/message-pusher#106]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
PushMe是一个新的安卓消息客户端，通过web接口，轻松发送消息到安卓手机，支持离线消息，兼容企业微信、钉钉、飞书机器人。官网：https://push.i-i.me/

**应用场景**
各种监控通知消息

**Comment by xuanqb** [comment]
直接用自定义消息通道就行了 https://iamazing.cn/page/message-pusher-common-custom-templates

**Comment by songquanpeng** [comment]
赞同 xuanqb 的说法
