### ISSUE TITLE
请问多用户如何实现？

### ISSUE THREAD

**Issue by kknd222** [songquanpeng/message-pusher#11]
尤其是heroku，我看到前缀和openid是写死的，不会是开多个APP吧？
再就是我想单独针对关注了测试公众号的用户进行特定用户发送特定消息，这个得增加用户管理功能吧？

**Comment by songquanpeng** [comment]
1. 对于 Heroku 模式，目前只能使用配置环境变量的方式来保存信息（否则配置将在冻结重启后丢失），因此是写死的。
2. 对于普通模式，管理员登录后会出现添加新用户的配置按钮。
3. 要想对特定用户发送特定消息，需要知道其设定的前缀，相应的用户管理功能还没搞。

**Comment by kknd222** [comment]
收到！
