### ISSUE TITLE
配置无法保存

### ISSUE THREAD

**Issue by wubin2** [songquanpeng/message-pusher#12]
admin登录后修改密码等配置操作点击提交没反应无法保存到data.db里去

**Comment by Terry-Lzz** [comment]
我也是出现这个问题，点击“提交”没有反应。 部署步骤都是按照文档来的

**Comment by songquanpeng** [comment]
感谢反馈，正在尝试复现。我确认一下不是 Heroku 模式吧？

**Comment by songquanpeng** [comment]
我本地 Windows 试了一下，发现没问题，而且最近并没有更新。

我怀疑是权限问题，请确认程序的根目录下 data.db 是否创建以及其权限是否正常。

另外请问是用宝塔装的吗？如果是的话可以参见该 issue：https://github.com/songquanpeng/message-pusher/issues/7

**Comment by songquanpeng** [comment]
复现了，正在调查。

**Comment by songquanpeng** [comment]
如果仍有问题，请重开 issue，感谢反馈！
