### ISSUE TITLE
无法发送纯文本消息

### ISSUE THREAD

**Issue by Terry-Lzz** [songquanpeng/message-pusher#13]
根据教程里说明
“发送纯文本消息：直接 HTTP GET 请求 https://你的域名/你的前缀/消息，缺点是有字数限制，且只能是纯文本，这是微信消息的限制。”
经测试该方法发出去的消息依旧是markdown消息，不是传统文本消息

**Comment by songquanpeng** [comment]
如果是直接 `https://你的域名/你的前缀/消息`，消息会作为描述进行处理，这里是没有经过 Markdown 解析的，参见：https://github.com/songquanpeng/message-pusher/blob/c4a1e26c6018c826ad250214957e49cb00aa8c5e/routers/user.js#L24-L31

为避免误解，这里说明一下，Markdown 消息指的是推送点击后跳转至一个网页，里面显示解析后的 Markdown 的消息方式，其可以包含标题，描述和正文；文本消息仅有标题和描述，没有正文，其中标题和描述部分直接显示在微信的推送卡片上，是没办法加样式的。

由此可见这里定义的所谓 Markdown 消息相当于拓展后的文本消息，区别仅在于 Markdown 消息有正文（由 content 字段指定）。因此按照这个定义，只要能发送 Markdown 消息，就肯定能兼容纯文本消息。

**Comment by songquanpeng** [comment]
如果还有问题请重开 issue，这里先关啦

**Comment by Terry-Lzz** [comment]
我是想发送那种纯文本消息，就跟我们平时聊天窗口发送的消息一样的。

**Comment by songquanpeng** [comment]
那种就不是模板消息了，受微信 API 限制，并不能主动推送，详见：https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Passive_user_reply_message.html

**Comment by Terry-Lzz** [comment]
> 
> 
> 那种就不是模板消息了，受微信 API 限制，并不能主动推送，详见：https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Passive_user_reply_message.html

不好意思，没有说清楚发送渠道。
我是指通过企业微信应用，给指定用户或者全体成员发送消息，测试好像发不了纯文本消息，只能发卡片。

**Comment by songquanpeng** [comment]
了解了，请问发送此类纯文本消息的应用场景是什么？

**Comment by Terry-Lzz** [comment]
> 
> 
> 了解了，请问发送此类纯文本消息的应用场景是什么？

消息展示比较直接，适用于一些单文本的结果输出，不需要复杂排版展示的。因为卡片消息还需要点进去看详情，普通文本消息展示比较直接，并且也支持聊天记录的合并转发。

**Comment by songquanpeng** [comment]
> 因为卡片消息还需要点进去看详情

可以直接放到 description 里，也是不需要点进去看的。

> 支持聊天记录的合并转发

卡片消息也是可以的，如下：
![image](https://user-images.githubusercontent.com/39998050/125802058-e49d6969-7a4d-4532-8d03-fb58cea81935.png)

**Comment by Terry-Lzz** [comment]
> 可以直接放到 description 里，也是不需要点进去看的。

如果想发送纯文本消息的话，应该怎么弄呢？

**Comment by songquanpeng** [comment]
GET 方式：`https://push.yourdomain.com/prefix/?&title=消息标题&description=纯文本内容`
POST 方式，详见：https://github.com/songquanpeng/message-pusher#发送消息的方式

**Comment by songquanpeng** [comment]
如果问题已经解决，请关闭 issue；如果尚未，请继续反馈~

**Comment by Terry-Lzz** [comment]
> 
> 
> GET 方式：`https://push.yourdomain.com/prefix/?&title=消息标题&description=纯文本内容`
> POST 方式，详见：[https://github.com/songquanpeng/message-pusher#发送消息的方式](https://github.com/songquanpeng/message-pusher#%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF%E7%9A%84%E6%96%B9%E5%BC%8F)

我的意思是非卡片式的纯文本消息

**Comment by songquanpeng** [comment]
暂时还不支持



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月20日(星期二) 中午11:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [songquanpeng/message-pusher] 无法发送纯文本消息 (#13)





  
GET 方式：https://push.yourdomain.com/prefix/?&amp;title=消息标题&amp;description=纯文本内容
 POST 方式，详见：https://github.com/songquanpeng/message-pusher#发送消息的方式
  
我的意思是非卡片式的纯文本消息
 
&mdash;

**Comment by Terry-Lzz** [comment]
好的，谢谢。
