### ISSUE TITLE
无效的 access token

### ISSUE THREAD

**Issue by mmcer** [songquanpeng/message-pusher#14]
按照文档配置好所有的内容，去验证是否可以收到 Hi 信息时，返回 无效的 access token。
1、自己的服务器
2、已开启 https，其实 http 也是一样的错误
3、修改代码，输出具体的错误，common/message.js 里 message.token 输出是 undefined。
4、无论是测试号还是企业号均是该错误
5、访问服务器的 verify 地址，输出 verification failed。修改代码打印详细错误，发现是 const { signature, timestamp, nonce, echostr } = req.query; 里 signature 输出是 undefined
6、文档里说是要在微信测试号里输入信息后，点击验证按钮，但是实际上我发现这块并不是显示验证按钮，而是提交按钮

求大佬帮忙分析下是怎么回事

**Comment by songquanpeng** [comment]
收到，不过我现在手头没有环境，可能需要晚上回去后才能处理

**Comment by songquanpeng** [comment]
> 访问服务器的 verify 地址

这个不是你自己去访问的，而是交给微信的服务器去访问的，如图：
![image](https://user-images.githubusercontent.com/39998050/127603615-668c1b55-057e-4ccc-b076-e6640deb205e.png)

**Comment by songquanpeng** [comment]
看样子是你设置了 ACCESS TOKEN，如果这样的话需要在传入的参数中加入 ACCESS TOKEN，例如：
`https://yourserver.cn/user_prefix/?type=test&description=Hi!&token=你的 TOKEN`

或者在设置里将其置空：
![image](https://user-images.githubusercontent.com/39998050/127604375-34d4c3a4-bbad-4f2e-9eb9-deff767a00ab.png)

**Comment by mmcer** [comment]
传递 token 后解决问题了，可以关闭了，多谢大佬~
也麻烦大佬更新下 readme.md 说明下，也方便大家留意这个。

**Comment by songquanpeng** [comment]
已更新。
