### ISSUE TITLE
已配置完成并成功推送，首页仍提醒未完成配置

### ISSUE THREAD

**Issue by sea72** [songquanpeng/message-pusher#17]
如题
用起来不错，感谢一下

**Comment by songquanpeng** [comment]
谢谢反馈，你找到了一个 bug，原因在于程序只检查了是否配置了微信测试号，没有考虑到其他推送方式。

该 bug 预计今晚修复。

**Comment by sea72** [comment]
另
1.纯文本的消息推送方式，似乎不支持token
2.点击消息查看详情会跳转到网页么？这点似乎与serverchan有所不同。且跳转过程中会提示 将要访问非官方网站，影响体验

**Comment by songquanpeng** [comment]
> 纯文本的消息推送方式，似乎不支持token

这是一个 bug，也是今天发现的，见 #16，临时的解决方法是：`https://你的域名/你的前缀/?title=消息&token=***`

> 点击消息查看详情会跳转到网页么？这点似乎与serverchan有所不同。且跳转过程中会提示 将要访问非官方网站，影响体验

这是因为 Markdown 消息的内容需要一个额外的网页来展示，但是对于纯文本消息，确实不该提供跳转链接，问题代码在于：
https://github.com/songquanpeng/message-pusher/blob/c98e332d185592eae3d71c7acb7015b402567513/common/wechat-corp.js#L57-L61

这几个问题都预计于今晚修复。

**Comment by songquanpeng** [comment]
> 点击消息查看详情会跳转到网页么？这点似乎与serverchan有所不同。且跳转过程中会提示 将要访问非官方网站，影响体验

我看了微信的文档，必须要传入一个链接，所以这个没办法。

**Comment by sea72** [comment]
看了眼你的实现方式，msgtpye是用的textcard。有没有考虑过开放msgtype为markdown类型的，我看微信的文档，markdown类型的似乎是能直接显示所有内容，而不需要url跳转消息服务器去显示content的。

**Comment by sea72** [comment]
textcard能直接显示的是description-512byte,
markdown能直接显示的是content-2048byte,
似乎是这样，我看我能不能验证一下
![捕获1](https://user-images.githubusercontent.com/24682001/129754314-12aef653-6613-4755-9d09-ed4349eb601e.PNG)

**Comment by songquanpeng** [comment]
嗯，当时是考虑到它的 markdown 消息支持的语法不全，不过应该把选择权交给用户，能直接显示所有消息内容也挺好的。

**Comment by sea72** [comment]
可以默认原来那样，这里引入一个高级设置。省去一步跳转步骤，间接避免微信那个提示。
另，针对那个提示，我去添加了安全域名，本以为能解决，但是没用。提交了人工审核，还没收到回复。
目测可能需要备案域名，我没有备案域名，如果你有，可以测试下。

**Comment by songquanpeng** [comment]
我的备案了，是可以直接跳转的。

**Comment by sea72** [comment]
好吧，那你可以在readme里说一下，因为可能不少人域名没备案。
Many Thx.

**Comment by songquanpeng** [comment]
> 嗯，当时是考虑到它的 markdown 消息支持的语法不全，不过应该把选择权交给用户，能直接显示所有消息内容也挺好的。

Okay，上述功能实现时一并更新文档。

**Comment by songquanpeng** [comment]
https://github.com/songquanpeng/message-pusher/issues/16#issuecomment-900756824

貌似不备案也是可以的。

**Comment by sea72** [comment]
可以跳转啊，不过有个“非微信官方网页，请确认是否继续访问”的提示
And request a feature, show wechat official access token(corpToken) in configuration tab for users' own interest , maybe set it as input:disabled. I can't fulfill myself. :)

**Comment by songquanpeng** [comment]
> 可以跳转啊，不过有个“非微信官方网页，请确认是否继续访问”的提示

之后 Markdown 卡片功能上线后就不用跳转网页了。

> And request a feature, show wechat official access token(corpToken) in configuration tab for users' own interest , maybe set it as input:disabled. I can't fulfill myself. :)

corpToken 是会过期的，我记得只有两个小时左右，如果需要这个 corpToken 做其他事情的话，将来可以加一个 API。

**Comment by sea72** [comment]
我看了data.db里是没有corpToken的，我不会nodejs，折腾了一下没找到获取方法。有什么方法能读到么？至于这个feature，如果以后有人再提出了，再实现吧，不是很紧急。

**Comment by songquanpeng** [comment]
因为 corpToken 是会过期的，所以就没入库。

**Comment by songquanpeng** [comment]
放到内存缓存里去了。

**Comment by cn0068** [comment]
> textcard能直接显示的是description-512byte,
> markdown能直接显示的是content-2048byte,
> 似乎是这样，我看我能不能验证一下
> ![捕获1](https://user-images.githubusercontent.com/24682001/129754314-12aef653-6613-4755-9d09-ed4349eb601e.PNG)

请问这个卡片形式推送到微信是如何实现的？

**Comment by songquanpeng** [comment]
@cn0068 这个还未实现，上面的图片是微信的文档里面的示例。

**Comment by sea72** [comment]
我试了一下，markdown形式的消息推送到普通微信无法显示，必须下载企业微信。这样一来，意义不是很大了 @songquanpeng

**Comment by sea72** [comment]
> 我试了一下，markdown形式的消息推送到普通微信完全无法显示，必须下载企业微信。这样一来，意义不是很大了 @songquanpeng

ps 微信版本8.0.1

**Comment by songquanpeng** [comment]
感谢反馈，那这样的话确实意义不大了。

**Comment by cn0068** [comment]
> 我试了一下，markdown形式的消息推送到普通微信完全无法显示，必须下载企业微信。这样一来，意义不是很大了 @songquanpeng

请问如何推送markdown消息到微信？我有企业微信

**Comment by sea72** [comment]
@cn0068 等Owner更新吧，我是自己调用微信api试了下效果
