### ISSUE TITLE
请问一下，后续会公布heroku的搭建方法吗

### ISSUE THREAD

**Issue by Ecalose** [songquanpeng/message-pusher#2]
注意到演示站是用的heroku，所以有了亿点点想法

**Comment by songquanpeng** [comment]
不行的，30 分钟没有请求的话就会被冻结，之后再次启动数据就丢了

**Comment by songquanpeng** [comment]
搭建的话你直接导入该项目就可以用，啥代码都不用改的

**Comment by Ecalose** [comment]
> 不行的，30 分钟没有请求的话就会被冻结，之后再次启动数据就丢了

啊这，我记得其他的heroku项目也遇到了这样的问题，他们好像是通过使用.sh等方式解决这个问题的
[https://github.com/qkqpttgf/OneManager-php](url)
[https://github.com/mixool/kuhero](url)
[https://github.com/Baiyuetribe/kamiFaka](url)
最后一个项目为发卡站，它的原理我没看懂，不过它的网站也并不会还原；
希望这些能对老哥有帮助

**Comment by songquanpeng** [comment]
好的，我抽时间看一下，如果 work 的话会整理相应的教程，谢谢

**Comment by Ecalose** [comment]
> 好的，我抽时间看一下，如果 work 的话会整理相应的教程，谢谢

嗯嗯，辛苦老哥了

**Comment by songquanpeng** [comment]
我查了一下，有些是通过每隔一段时间自动给直接发一个请求来避免冻结的，但是这会受到总免费时长（550+450，这额外的 450 要求你帮你银行卡）的限制，而且有因为滥用而导致被封号的风险。

另一种方法是通过设置环境变量，这样这话就不能添加任意多的用户了，不过对于单个用户来说还是可行的。

以上两种方法本周末我应该都会去做，让用户自由选择采用哪种方法。

非常感谢你的建议。

**Comment by songquanpeng** [comment]
通过设置环境变量来保存配置信息的方法已经搞定了

**Comment by Ecalose** [comment]
> 通过设置环境变量来保存配置信息的方法已经搞定了

大佬🐂🍺

**Comment by Ecalose** [comment]
> 通过设置环境变量来保存配置信息的方法已经搞定了

貌似部署后虽然推送成功了，但貌似在微信公众号的那个接口配置仍然显示错误

**Comment by songquanpeng** [comment]
> > 通过设置环境变量来保存配置信息的方法已经搞定了
> 
> 貌似部署后虽然推送成功了，但貌似在微信公众号的那个接口配置仍然显示错误

因为今天我获取 token 次数过多，被限制了，因此仅测试了在 heroku 上推送邮件消息，请问具体是什么错误

**Comment by Ecalose** [comment]
> > > 通过设置环境变量来保存配置信息的方法已经搞定了
> > 
> > 
> > 貌似部署后虽然推送成功了，但貌似在微信公众号的那个接口配置仍然显示错误
> 
> 因为今天我获取 token 次数过多，被限制了，因此仅测试了在 heroku 上推送邮件消息，请问具体是什么错误

消息推送是没问题的，但在微信公众号平台验证token时却是失败的
[https://i.loli.net/2021/01/31/QZeyxzmoIC3GkaS.png](url)

**Comment by songquanpeng** [comment]
@Ecalose 我刚刚试了一下，显示配置成功，是不是验证 url 填错了？

**Comment by Ecalose** [comment]
> @Ecalose 我刚刚试了一下，显示配置成功，是不是验证 url 填错了？

尴尬，url忘加verify了，现在ok了

**Comment by Ecalose** [comment]
话说这个测试公众号好丑啊(雾，网上查了查貌似没有办法修改名字和头像，只能用那个

**Comment by songquanpeng** [comment]
对的，使用邮件推送会好一些。之前在 V 站有人提议可以自己申请微信企业号，里面可以自建应用号，我还没来得及适配。

**Comment by Ecalose** [comment]
好家伙，等一手老哥的企业号
