### ISSUE TITLE
什么时候可以支持arm的机器啊

### ISSUE THREAD

**Issue by szsyzx** [songquanpeng/message-pusher#21]
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by songquanpeng** [comment]
这是 Docker 的报错是么？我还没有给 arm 打包。

**Comment by songquanpeng** [comment]
这个看一下哈：https://stackoverflow.com/questions/72152446/warning-the-requested-images-platform-linux-amd64-does-not-match-the-detecte

**Comment by szsyzx** [comment]
是的docker报错
![image](https://user-images.githubusercontent.com/21995452/186058576-f17658c6-1e15-474e-b5a3-5191cf7390c7.png)
老大您能给arm打个包么

**Comment by songquanpeng** [comment]
我刚刚查了下，好像本身是支持的？试一下这里面提到的方法：https://stackoverflow.com/questions/72152446/warning-the-requested-images-platform-linux-amd64-does-not-match-the-detecte

**Comment by szsyzx** [comment]
老大有联系方式么 小白的我问他很多需要您的远程指导

**Comment by songquanpeng** [comment]
直接 issue 问好一些，也可以帮到其他人

**Comment by szsyzx** [comment]
![image](https://user-images.githubusercontent.com/21995452/186059846-0556d8eb-bfe2-406d-ac90-4de5db044055.png)
请问这个错误如何解决
![image](https://user-images.githubusercontent.com/21995452/186060191-5540b386-6d6c-4f5d-9d6d-8f421cc562d6.png)

**Comment by songquanpeng** [comment]
你忘记修改 `/path/to/nginx.conf` 了，你需要把这个替换成你本地服务器上的路径，替换后是：
`sudo ln -s /root/message-pusher/nginx.conf /etc/nginx/sites-enabled/message-pusher.conf`

或者你直接把这个 nginx.conf 文件复制到 `/etc/nginx/sites-enabled/` 也可以。

**Comment by szsyzx** [comment]
/etc/nginx/sites-enabled/这个路径不存在啊 需要自己创建吗

**Comment by songquanpeng** [comment]
那说明你没装 Nginx，你要是不需要 HTTPS 的话可以不装 Nginx

**Comment by songquanpeng** [comment]
我有空后打包一个更完整的 Docker 镜像吧，里面直接包含好 Nginx
