### ISSUE TITLE
certbot申请证书求助

### ISSUE THREAD

**Issue by szsyzx** [songquanpeng/message-pusher#23]
certbot申请证书：sudo certbot --nginx

具体如何使用啊 我已经安装了cerbot

![image](https://user-images.githubusercontent.com/21995452/186062759-57a0f200-1ad2-47ce-9755-c14f18bad8b5.png)

**Comment by songquanpeng** [comment]
Ubuntu 的话试一下这个：` sudo apt-get install python3-certbot-nginx`

BTW，遇到报错第一时间 Google 搜一下报错信息就大概率能解决问题。

**Comment by szsyzx** [comment]
好的谢谢老大

**Comment by songquanpeng** [comment]
还有，这种文本信息别截图，直接 Markdown 包成代码块贴上来好一些，有利于别人用搜索引擎搜到这个 issue。
