### ISSUE TITLE
访问https://你的域名/前缀/Hi 请问这个前缀是什么意思啊

### ISSUE THREAD

**Issue by szsyzx** [songquanpeng/message-pusher#24]
访问https://你的域名/前缀/Hi 请问这个前缀是什么意思啊

![image](https://user-images.githubusercontent.com/21995452/186064833-e45d81f8-3664-4a21-b533-8c9311348025.png)
我yj已经设置好了企业微信的参数 我想测试是否可以收到消息

**Comment by songquanpeng** [comment]
前缀是为了区分多个用户，如果就你一个用户，随便设置就好。

**Comment by szsyzx** [comment]
![DB981569-C916-4ecc-9FBE-9C2616B89A76](https://user-images.githubusercontent.com/21995452/186076122-bd274ec7-fc4c-48b8-8609-7e15a80a5c32.png)
企业微信配置信息都正确，使用默认用户测试提示这个

**Comment by songquanpeng** [comment]
如果配置没问题的话，估计是因为国外的服务器的原因：

https://developers.weixin.qq.com/community/develop/doc/0002ec5b9c4e383f088604eb956400

**Comment by szsyzx** [comment]
难道真的是国外服务器的问题吗？老大要不我提供台国外服务器您试下？

**Comment by songquanpeng** [comment]
和地区也有关系，微信肯定是有风控的。

但是我不能完全确定，这个问题也是第一次见。

你可以配置一下微信测试号的推送方式试一下，看看那个是不是也是这种情况。

**Comment by szsyzx** [comment]
![F3697197-BD8C-4034-8163-38C1473247DF](https://user-images.githubusercontent.com/21995452/186080162-58d9e06c-7c5c-4c07-86f7-69da8f544bf2.png)
微信测试号这2个数值对吧？

**Comment by songquanpeng** [comment]
1. 首先前往[此页面](https://mp.weixin.qq.com/debug/cgi-bin/sandboxinfo?action=showinfo&t=sandbox/index)拿到 APP_ID 以及 APP_SECRET。
2. 使用微信扫描下方的测试号二维码，拿到你的 OPEN_ID。
3. 新增模板消息模板，模板标题随意，模板内容填 `{{text.DATA}}`，提交后可以拿到 TEMPLATE_ID。
4. 填写接口配置信息，URL 填 `https://你的域名/前缀/verify`，TOKEN 随意，先不要点击验证。（前缀默认和用户名相同）
5. 现在访问 `https://你的域名/`，默认用户为 admin，默认密码为 123456，登录后根据系统提示完成配置，之后点击提交按钮。
6. 之后回到微信公众平台测试号的配置页面，点击验证。

**Comment by szsyzx** [comment]
![image](https://user-images.githubusercontent.com/21995452/186083194-f2f18e0f-aee0-44b0-9212-2f87ad6926e7.png)
搭建在Heroku上显示此错误

**Comment by songquanpeng** [comment]
那这个就是明确的 IP 被 ban 了。

我之前测试的时候使用 Heroku 是没问题的。

**Comment by szsyzx** [comment]
好吧感谢您的热心解答

**Comment by songquanpeng** [comment]
那我感觉之前的 ECONNRESET 可能有其他原因？

如果有国内服务器的话还是推荐放到国内服务器上吧。

**Comment by szsyzx** [comment]
我的这些4+24的服务器都是甲骨文云的 白嫖的

**Comment by songquanpeng** [comment]
配置确实挺好的

**Comment by szsyzx** [comment]
您要是需要我可以送您一个账号![image](https://user-images.githubusercontent.com/21995452/186085074-336309b1-9918-453c-b505-96da69449ae0.png)

**Comment by songquanpeng** [comment]
目前服务器够用了，谢谢
