### ISSUE TITLE
腾讯云的上海服务器搭建被阻止访问

### ISSUE THREAD

**Issue by szsyzx** [songquanpeng/message-pusher#25]
腾讯云的上海服务器搭建被阻止访问
![image](https://user-images.githubusercontent.com/21995452/186093558-a3c221d7-8753-477c-b658-15f491e5db5c.png)

**Comment by songquanpeng** [comment]
这就很离谱了，我用的是腾讯云香港和广州都没问题。

**Comment by szsyzx** [comment]
是啊 我快绝望了 国内外的服务器都不能用

**Comment by songquanpeng** [comment]
企业微信设置白名单可解：https://developers.weixin.qq.com/community/develop/doc/000aa2c8774df86066ea3b77251800?_at=6T7zU

**Comment by songquanpeng** [comment]
我简单搜了一下，好像这个是最近六七月的事情

**Comment by szsyzx** [comment]
我去试试看下

**Comment by szsyzx** [comment]
![image](https://user-images.githubusercontent.com/21995452/186097397-a10af72a-5b84-4fa0-abb8-6fdb4c18d87e.png)
把服务器IP地址添加到企业可信IP解决了此问题
