### ISSUE TITLE
企业微信应用消息推送，不带图标呢，而且还自带链接，点一下就空白

### ISSUE THREAD

**Issue by wfniub** [songquanpeng/message-pusher#26]
企业微信应用消息推送，不带图标呢，而且还自带链接，点一下就空白

**Comment by songquanpeng** [comment]
不好意思现在才看到这个 issue，
1. 不带图标的问题我没有遇到，可能是企业微信的设置页面没有设置应用图标？
2. 点一下不应该空白，应该是跳转到 Message Pusher 的网站，这个自带链接是企业微信要求的，如果你发送的是 Markdown 消息跳转后将是消息的内容页面。
