### ISSUE TITLE
可以更新一下docker 部署吗

### ISSUE THREAD

**Issue by heishanmao** [songquanpeng/message-pusher#27]
vim, certbot 没有安装
/etc/nginx/sites-enabled/message-pusher.conf 这个路径没有

跑不起来呀

**Comment by songquanpeng** [comment]
之前想的是 docker 里的镜像只暴露一个 HTTP 端口，确实全部放进去好一些，有空搞一下

**Comment by heishanmao** [comment]
不装证书的话，http也可以用吗？docker 安装后之后3000页面配置是不是就可以了？看教程以为是必须https

**Comment by songquanpeng** [comment]
1. 可以用
2. 是的


不过还是推荐在宿主机配置一下证书



---Original---
From: ***@***.***&gt;
Sent at: 2022年10月23日(Sun) AM9:43
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/message-pusher] 可以更新一下docker 部署吗 (Issue #27)




 
不装证书的话，http也可以用吗？docker 安装后之后3000页面配置是不是就可以了？看教程以为是必须https

**Comment by heishanmao** [comment]
THX, 明白了。Host有证书就可以啦～
