### ISSUE TITLE
可信任IP配置

### ISSUE THREAD

**Issue by heishanmao** [songquanpeng/message-pusher#28]
企业微信尝试发送test的时候返回，more info at https://open.work.weixin.qq.com/devtool/query?e=60020
需要配置可信任IP，又要求先完成配置可信任域名。
    配置可信域名需完成域名归属认证
    1. Download "WW_verify_*****.txt
    2.将此文件放到www根目录

卡在了第二步，docker exec 进入后，直接放到根目录不对，想问下这个www根目录的docker路径是？

**Comment by songquanpeng** [comment]
1. 这个报错我还没遇到过，谢谢反馈。
2. 如果是要放这个文件的话，放到项目根目录下的 public 文件夹内。

**Comment by songquanpeng** [comment]
我最近重新配置了下，发现确实需要配置可信 IP 了。

需要注意的是，配置可信任域名和你部署的服务的域名可以不是同一个，所以这里只需要用你的其他网站完成域名验证即可。
