### ISSUE TITLE
字数限制

### ISSUE THREAD

**Issue by GH3a** [songquanpeng/message-pusher#3]
![IMG_0051](https://user-images.githubusercontent.com/64625271/105321431-69398780-5c02-11eb-9a19-c0548aaebc97.JPG)
发送的消息，如果超出字数限制就会不显示了。

**Comment by songquanpeng** [comment]
这是微信模板消息的字数限制，貌似是 200 字，等我实现好 Markdown 消息后可以将主要内容放到正文
