### ISSUE TITLE
企业微信应用消息无法发送

### ISSUE THREAD

**Issue by iskycc** [songquanpeng/message-pusher#30]
企业微信应用消息配置正常，无法测试发送消息，报错：`错误：access_token missing, hint: [1670371158347280850760093], from ip: x.xx.xxx.xx, more info at https://open.work.weixin.qq.com/devtool/query?e=41001` ，测试使用相同的配置其他开源项目可以正常发送通知

**Comment by iskycc** [comment]
百度说是因为ip不在白名单，但是这是我很久之前就申请的企业微信应用，那个时候还不需要ip白名单，而且我用的一个新的服务器部署的一个其他开源项目是可以发送消息的

**Comment by songquanpeng** [comment]
这是因为 Access Token 没有正常获取到，两种可能：
1. 配置有问题。
2. 境外服务器被微信 ban 了。

**Comment by iskycc** [comment]
> 这是因为 Access Token 没有正常获取到，两种可能：
> 
> 1. 配置有问题。
> 2. 境外服务器被微信 ban 了。

可是我尝试了把配置复制到其他开源项目可以使用，再者服务器为国内腾讯云、应该不可能被ban

**Comment by songquanpeng** [comment]
这就很奇怪了，我再测试一下尝试复现，感谢反馈。用的版本是哪一个呢？

**Comment by iskycc** [comment]
> > > 这是因为 Access Token 没有正常获取到，两种可能：
> > > 
> > > 1. 配置有问题。
> > > 2. 境外服务器被微信 ban 了。
> > 
> > 
> > 可是我尝试了把配置复制到其他开源项目可以使用，再者服务器为国内腾讯云、应该不可能被ban
> 
> 同一台服务器吗？

并非同一台服务器，用的版本是最新版docker镜像，如果方便麻烦您留个邮箱我给您发我的数据方便定位问题

**Comment by songquanpeng** [comment]
最好用同一台服务器测试，控制变量。

好的：`i@justsong.cn`

**Comment by iskycc** [comment]
> 最好用同一台服务器测试，控制变量。
> 

已在同服务器下部署类似于message-pusher的开源项目，测试结果相同，相关数据已通过邮箱发送，请查收

**Comment by iskycc** [comment]
服务器docker restart重启容器重新登录，问题已解决，感谢开发者帮忙测试

**Comment by songquanpeng** [comment]
按理说不应该需要重启容器，我这边继续调查一下。

谢谢反馈。

**Comment by songquanpeng** [comment]
确实是代码的问题，已修复，现在应不用重启也能正常获取 token

**Comment by iskycc** [comment]
> 确实是代码的问题，已修复，现在应不用重启也能正常获取 token

收到
