### ISSUE TITLE
新功能请求：支持 Web 端查看推送的消息

### ISSUE THREAD

**Issue by iskycc** [songquanpeng/message-pusher#32]
是否可以增加一个功能：任何通过本项目接口发出的通知可以在Web端翻阅查看，可以由超级管理员选择是否开启。应用场景为将本项目自身打造成一个可以接收推送的接口。我想这个功能实现起来最麻烦的地方是通知太多了sqlite是否能满足性能要求，其他的应该不算难。

**Comment by songquanpeng** [comment]
好想法，之后有时间搞一下，issue 先开着



---Original---
From: ***@***.***&gt;
Sent at: 2022年12月9日(Fri) AM6:40
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/message-pusher] 是否可以增加一个功能 (Issue #32)




 
是否可以增加一个功能：任何通过本项目接口发出的通知可以在Web端翻阅查看，可以由超级管理员选择是否开启。应用场景为将本项目自身打造成一个可以接收推送的接口。我想这个功能实现起来最麻烦的地方是通知太多了sqlite是否能满足性能要求，其他的应该不算难。

**Comment by songquanpeng** [comment]
SQLite 这个不用担心，而且系统是支持使用其他数据库的，设置 `SQL_DSN` 环境变量就好了，详见 README。

主要工作量是在前端，但是也不算麻烦。

**Comment by songquanpeng** [comment]
已支持在 Web 端查看消息，新版本今天内会放出
