### ISSUE TITLE
增加 arm 版本的 release 可执行文件和 Docker 镜像

### ISSUE THREAD

**Issue by bigmangos** [songquanpeng/message-pusher#36]
您好，能否新增一个arm版本的二进制和docker镜像

**Comment by songquanpeng** [comment]
好的，我看一下要怎么搞。只是我没有 arm 设备，不太好验证是否 okay。

**Comment by bigmangos** [comment]
我可以帮忙验证，谢谢

**Comment by songquanpeng** [comment]
好的谢谢，到时候就麻烦你了

**Comment by songquanpeng** [comment]
请问你是什么系统呢？另外我会先在这个项目上 https://github.com/songquanpeng/gin-template 做测试，没问题之后再迁移到本项目。

**Comment by bigmangos** [comment]
➜  web git:(master) uname -a
Linux instance-20210605-2208 5.10.0-13-arm64 #1 SMP Debian 5.10.106-1 (2022-03-17) aarch64 GNU/Linux

**Comment by songquanpeng** [comment]
请测试：https://github.com/songquanpeng/gin-template/releases/download/v0.2.9/gin-template-arm64 以及 `justsong/gin-template:latest`

谢谢

**Comment by TChuJiu** [comment]
> Reference in

 ARMV8 64位 验证正常使用

Linux gin-template 5.10.134 #0 SMP PREEMPT Mon Aug 1 02:46:24 2022 aarch64 Linux

![image](https://user-images.githubusercontent.com/32093961/208913751-78c9be74-519b-4c99-b26e-5157e3c5bb78.png)

**Comment by songquanpeng** [comment]
好的辛苦了

**Comment by TChuJiu** [comment]
> 



> 好的辛苦了

十分期待~~，感谢~~

**Comment by songquanpeng** [comment]
`v0.3.1` 已经在打包了，arm 版本的镜像需要大概 1h 才能打包好。

**Comment by bigmangos** [comment]
测试可用，已经跑起来了，感谢~

![image](https://user-images.githubusercontent.com/16350350/209059457-fa533117-b127-4665-96b2-5b15ba18f50c.png)

**Comment by songquanpeng** [comment]
好的，谢谢反馈。另外请问这是什么管理工具呀？

**Comment by bigmangos** [comment]
> 好的，谢谢反馈。另外请问这是什么管理工具呀？

Portainer https://www.portainer.io/

**Comment by songquanpeng** [comment]
好的谢谢
