### ISSUE TITLE
能不能支持自定义的消息卡片URL

### ISSUE THREAD

**Issue by JayFang1993** [songquanpeng/message-pusher#38]
https://github.com/songquanpeng/message-pusher/blob/e178d5a6222289917f41c6bf56f5b627bb7faded/controller/message.go#L125

很多消息渠道支持URL落地页，能否支持自定义消息URL，不走默认的消息页面

**Comment by songquanpeng** [comment]
是指消息渠道自带的消息详情页面是吗？

**Comment by songquanpeng** [comment]
哦，是指手动指定 URL 是吗？这个可以支持，也挺简单的。

**Comment by JayFang1993** [comment]
前者，比如企业微信渠道，点击消息卡片的跳转页面可以走我指定的🔗

**Comment by JayFang1993** [comment]
是的，对于设置 message.URL不为空就跳过这段逻辑

**Comment by songquanpeng** [comment]
了解了，感谢反馈，明天就可以实现。

我可以问一下这种有什么应用场景吗？

**Comment by JayFang1993** [comment]
有啊，自定义消息提醒带落地页的很常见，单纯消息卡片可以展示的消息内容有限

**Comment by songquanpeng** [comment]
这样，了解了，感谢反馈~

**Comment by JayFang1993** [comment]
https://github.com/songquanpeng/message-pusher/pull/39

**Comment by songquanpeng** [comment]
已合并。

**Comment by songquanpeng** [comment]
已推送 v0.3.3-alpha。

**Comment by JayFang1993** [comment]
什么时候部署下呗 ，直接用的你的服务😂

**Comment by songquanpeng** [comment]
已更新 https://msgpusher.com/。

不过需要说明的是这个部署版本是禁用了消息渲染的，这是为了防止有人发布不好的消息。
