### ISSUE TITLE
如何发送到其他邮箱去?

### ISSUE THREAD

**Issue by lijiazhiren** [songquanpeng/message-pusher#44]
我绑定了QQ邮箱 现在只能发给自己
看了一下 好像没有设置收件人的地方

**Comment by songquanpeng** [comment]
目前只能发到自己经过验证的邮箱，主要是为了防止滥用。

将来可以考虑添加一个选项，允许管理员启用设置收件人的功能

**Comment by lijiazhiren** [comment]
> 目前只能发到自己经过验证的邮箱，主要是为了防止溢出。
> 
> 将来可以考虑添加一个选项，允许管理员启用设置收件人的功能

现在

> 目前只能发到自己经过验证的邮箱，主要是为了防止滥用。
> 
> 将来可以考虑添加一个选项，允许管理员启用设置收件人的功能

现在看到说能绑QQ邮箱我就只试了这个
支持绑其他邮箱吗？

**Comment by songquanpeng** [comment]
可以的，只要服务器能发过去就行。

**Comment by songquanpeng** [comment]
已支持发送到其他邮箱，为避免滥用，该功能需要管理员手动为用户启用（用户管理->更多->授予发送任意邮件的权限），管理员用户无此限制。
