### ISSUE TITLE
增加消息分组功能

### ISSUE THREAD

**Issue by xracoo** [songquanpeng/message-pusher#46]
建议：每个分组可选择或指定对应的推送规则。推送URL增加group字段，然后消息根据指定的推送规则分发。

**Comment by songquanpeng** [comment]
感谢反馈，我先想一下。

**Comment by songquanpeng** [comment]
目前的打算是新增一个推送渠道类型 `group`，可以设置里面包含的具体渠道以及目标接收者。

预计近期内实现。

**Comment by songquanpeng** [comment]
已实现：
![image](https://user-images.githubusercontent.com/39998050/236654643-509717de-a781-4cee-a952-f6d7fba4922c.png)
