### ISSUE TITLE
将企业微信应用消息接收主体允许放在请求行里进行自定义，并非写死在配置文件里

### ISSUE THREAD

**Issue by itrilogy** [songquanpeng/message-pusher#48]
这样可以增加应用的使用场景，例如生日提醒、工资提醒等等。

**Comment by songquanpeng** [comment]
是指指定接收者吗？这个好改，最近有时间的话会去实现一下。

**Comment by itrilogy** [comment]
是的，感觉这样小白们都可以用它创造很多特定场景的应用，非常值得期待。

从 Windows 版邮件发送

发件人: JustSong
发送时间: 2023年2月21日 16:45
收件人: songquanpeng/message-pusher
抄送: itrilogy; Author
主题: Re: [songquanpeng/message-pusher]=?UTF-8?Q?_=E5=B0=86=E4=BC=81=E4=B8=9A=E5=BE=AE=E4=BF=A1=E5=BA=94=E7=94=A8=E6=B6=88=E6=81=AF=E6=8E=A5=E6=94=B6=E4=B8=BB=E4=BD=93=E5=85=81=E8=AE=B8=E6=94=BE=E5=9C=A8=E8=AF=B7=E6=B1=82=E8=A1=8C=E9=87=8C=E8=BF=9B=E8=A1=8C=E8=87=AA=E5=AE=9A=E4=B9=89=EF=BC=8C=E5=B9=B6=E9=9D=9E=E5=86=99=E6=AD=BB=E5=9C=A8=E9=85=8D=E7=BD=AE=E6=96=87=E4=BB=B6=E9=87=8C?==?UTF-8?Q?_=28Issue_#48=29?=

是指指定接收者吗？这个好改，最近有时间的话会去实现一下。

**Comment by songquanpeng** [comment]
感觉也可以给其他消息推送方式加上。如果没有指定的话，就发给自己；如果指定的话就发给指定用户。

**Comment by itrilogy** [comment]
思路打开了

**Comment by songquanpeng** [comment]
已支持 `to` 字段来指定接收者。
