### ISSUE TITLE
单用户支持多个同类型的推送方式

### ISSUE THREAD

**Issue by 117503445** [songquanpeng/message-pusher#50]
我的使用场景是有多个钉钉群机器人，不同的事件需要调用不同的机器人。

现在单用户只能填写一个钉钉群机器人，所以我只能通过多个用户去实现这个需求。如果单用户支持多个钉钉群机器人，就会更加方便一点。

**Comment by songquanpeng** [comment]
感谢反馈，这个提议挺好的，之前貌似也有支持多邮箱的需求，等我之后有空后一并实现了

**Comment by songquanpeng** [comment]
已实现，今天会发版本，改动比较多，可能会有 bug。
