### ISSUE TITLE
企业微信应用号发送的消息，详情无法打开。

### ISSUE THREAD

**Issue by Ahorace** [songquanpeng/message-pusher#53]
企业微信应用号发送的消息，详情无法打开。
详情中链接来源为：http://localhost:3000/,广域网无法打开
能否支持微信公众号或小程序

**Comment by songquanpeng** [comment]
需要在后台设置域名：
![image](https://user-images.githubusercontent.com/39998050/230568516-b7f0a0d5-4dc5-49af-b238-8e3aeb9bb1e4.png)

微信测试号是支持的，工作号的话应该是 okay 的，但是因为我没有可以发送模板消息的权限公众号，所以无法实际测试。
小程序这个微信限制暂时没啥好办法。

**Comment by Ahorace** [comment]
已经设置正常了，公众号和微信测试号，配置上有差异吗？可以建个聊天沟通群组吗

**Comment by songquanpeng** [comment]
应该没差异，毕竟测试号就是微信官方拿来测试的，但是我毕竟没有测试过。暂时没有沟通群哈。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月7日(星期五) 下午4:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [songquanpeng/message-pusher] 企业微信应用号发送的消息，详情无法打开。 (Issue #53)





 
已经设置正常了，公众号和微信测试号，配置上有差异吗？可以建个聊天沟通群组吗

**Comment by Ahorace** [comment]
我使用了微信测试号可以正常使用，公众号只要是他的关注用户会自动获取用户 Open ID，模板消息无法自定义添加，需要从模板中选择的，添加后再回填生成的模板ID。
建议做个功能优化：
微信测试号支持输入配置多个用户 Open ID，支持已配置Open ID的消息群发；
远期能否适配支持微信公众号的消息推送。

**Comment by songquanpeng** [comment]
近期有计划更新该项目



---Original---
From: ***@***.***&gt;
Sent at: 2023年4月7日(Fri) Evening7:03
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/message-pusher] 企业微信应用号发送的消息，详情无法打开。 (Issue #53)




 
我使用了微信测试号可以正常使用，公众号只要是他的关注用户会自动获取用户 Open ID，模板消息无法自定义添加，需要从模板中选择的，添加后再回填生成的模板ID。
 建议做个功能优化：
 微信测试号支持输入配置多个用户 Open ID，支持已配置Open ID的消息群发；
 远期能否适配支持微信公众号的消息推送。
