### ISSUE TITLE
自定义数据库报错

### ISSUE THREAD

**Issue by Ubugs** [songquanpeng/message-pusher#54]
![image](https://user-images.githubusercontent.com/63220084/232968216-e7888636-74b6-42ea-be19-48a6e529992f.png)

**Comment by songquanpeng** [comment]
数据库版本是什么呢？我 check 一下

**Comment by Ubugs** [comment]
MySQL 8.0.24

**Comment by Ubugs** [comment]
错误的原因应该是mysql没有int64的数据结构

**Comment by songquanpeng** [comment]
是的，这里时间戳我用的是 int64 整型，已改为 bigint，修复版本 `v0.3.6-alpha` 已推送，当前正在构建。
