### ISSUE TITLE
配置SMTP不生效

### ISSUE THREAD

**Issue by thc1102** [songquanpeng/message-pusher#55]
数据库MySQL8
二次保存配置数据库不更新
![image](https://user-images.githubusercontent.com/63220084/233037549-dbed5374-995d-4b62-8baa-de32d356c28a.png)

**Comment by songquanpeng** [comment]
我测试一下

**Comment by songquanpeng** [comment]
问题已确认，GORM 相关的问题，已在处理。使用 SQLite 未发现该问题，导致没用测试到。

**Comment by songquanpeng** [comment]
感谢测试，GORM 挺不靠谱的感觉，我原以为对所有数据库都会有一致的表现。

**Comment by songquanpeng** [comment]
新版本 `v0.3.6-alpha.1` 已推送。
