### ISSUE TITLE
错误：dial tcp :587:connect: connection refused

### ISSUE THREAD

**Issue by aw179** [songquanpeng/message-pusher#56]
在腾讯云部署后，绑定邮箱会出现错误提示

错误：dial tcp :587:connect: connection refused

防火墙的587端口已打开
谢谢
![Screenshot 2023-04-19 at 5 25 27 PM](https://user-images.githubusercontent.com/30537744/233203683-316a160f-f08b-47df-86b5-d98cf678ce4f.jpg)

**Comment by songquanpeng** [comment]
587 是 SMTP 服务器的端口，和本机的端口没有关系。这些配置好了吗：
![image](https://user-images.githubusercontent.com/39998050/233228699-7dd2d182-935d-4f5b-a4ca-0affd7d985f1.png)

**Comment by aw179** [comment]
> 587 是 SMTP 服务器的端口，和本机的端口没有关系。这些配置好了吗：
> ![image](https://user-images.githubusercontent.com/39998050/233228699-7dd2d182-935d-4f5b-a4ca-0affd7d985f1.png)

请问配置SMTP的这个界面在哪里？不好意思我没找到

**Comment by songquanpeng** [comment]
这里：
![image](https://user-images.githubusercontent.com/39998050/233246019-624eadce-5d9f-4f55-adbc-1c468582d749.png)

**Comment by aw179** [comment]
> 这里：
> ![image](https://user-images.githubusercontent.com/39998050/233246117-29a1e091-fb5b-4a4c-971b-6c9cd6ed7e86.png)

![Screenshot 2023-04-19 at 10 55 13 PM](https://user-images.githubusercontent.com/30537744/233246500-d1eabc47-e1ad-4edd-a3c7-b1fa56a74329.jpg)
我的是这样的。我用docker run部署的

**Comment by songquanpeng** [comment]
你登录的不是管理员账号，系统初始化的时候会创建管理员账号：`admin` 和 `123456`

**Comment by aw179** [comment]
> 你登录的不是管理员账号，系统初始化的时候会创建管理员账号：`root` 和 `123456`，详见 README 的配置一节。

是我看漏了 谢谢！
