### ISSUE TITLE
每种推送方式都支持使用 `url` 字段指定详情链接

### ISSUE THREAD

**Issue by Ubugs** [songquanpeng/message-pusher#57]
类似于这种![image](https://user-images.githubusercontent.com/63220084/233779928-134cc214-172c-40c2-9cac-2206a3032159.png)

**Comment by songquanpeng** [comment]
这是 Bark 吗？有的推送方式是支持通过指定 `url` 字段来加上一个跳转链接的。我去看一下 Bark 的文档。

**Comment by Ubugs** [comment]
这样的话 每个推送方式都加上详情链接 也能增加通用型
![image](https://user-images.githubusercontent.com/63220084/233780162-5a458e00-6b48-44b3-974b-39a0668ac8f4.png)

**Comment by songquanpeng** [comment]
现在有些推送方式已经支持了添加详情 url，详见 #38，Bark 的话我今天搞定。

**Comment by songquanpeng** [comment]
已为 Bark 添加该功能，版本 `v0.3.6-alpha.2` 已推送。

**Comment by songquanpeng** [comment]
我刚刚检查了一下，支持 URL 的有：
+ [x] Bark
+ [ ] 企业微信群机器人
+ [ ] 钉钉群机器人
+ [ ] 飞书群机器人
+ [x] 企业微信应用号
+ [x] 微信测试号
+ [ ] Telegram
+ [ ] Discord
+ [ ] Client
+ [ ] 邮件

之后会陆续实现，感谢反馈。

**Comment by songquanpeng** [comment]
经过检查目前可以支持的都已经实现，如有遗漏，欢迎指出并重开 issue。
