### ISSUE TITLE
Web 端集成消息编辑 & 发送功能

### ISSUE THREAD

**Issue by Ahorace** [songquanpeng/message-pusher#59]
有个功能上的建议：
消息部分，能否加消息的富文本编辑和自主选择配置的渠道发送消息

**Comment by songquanpeng** [comment]
1. 富文本编辑指的是 Web 端加上富文本编辑的功能吗？不是很清楚，请补充描述。
2. `channel` 字段可以做到这一点，这个是已经支持的。

**Comment by Ahorace** [comment]
就是Web 端加上富文本编辑，使用的场景大概有2个：
1.历史消息列表，查看，重发，删除；新增一个编辑，调用富文本编辑，用户确定内容后再重发；
2.新发消息；使用富文本编辑发送内送，再自主选择已配置的渠道发送消息

**Comment by songquanpeng** [comment]
实际上就是在 Web 端集成一个消息推送的客户端，这个提议很好。

**Comment by songquanpeng** [comment]
已实现，已推送 `v0.4.4`，期待反馈。

截图：
![image](https://user-images.githubusercontent.com/39998050/236971995-7408cdd9-8a02-4c09-8c32-f99d8365dd27.png)
