### ISSUE TITLE
server酱已经用企业微信了

### ISSUE THREAD

**Issue by blair2020** [songquanpeng/message-pusher#6]
是不是服务号通道和测试号通道可能因微信下线模板消息而不可用
https://developers.weixin.qq.com/community/develop/doc/000a4e1df800d82acb9b7fb5e5b001
届时还能用吗？

**Comment by songquanpeng** [comment]
企业微信将来会适配，如果真的测试号也不能用模板消息了，我会尽快适配；现在也是支持邮件消息的，发送方式一样，完全不可用倒不至于。

不过我感觉，微信可能不会这样干，这会 break 很多服务。

**Comment by songquanpeng** [comment]
已经支持企业微信了。
