### ISSUE TITLE
使用企业微信应用号推送提示无效的渠道名称

### ISSUE THREAD

**Issue by shobalpeng** [songquanpeng/message-pusher#69]
最新版本docker部署，在推送设置里点测试可以正常发送消息，但是通过get访问url提示无效的渠道名称
{"message":"无效的渠道名称：corp_app","success":false}

**Comment by songquanpeng** [comment]
Okay，新版本改动有点多，我稍后调查一下这个问题。



---Original---
From: ***@***.***&gt;
Sent at: 2023年5月6日(Sat) Evening6:12
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/message-pusher] 使用企业微信应用号推送提示无效的渠道名称 (Issue #69)




 
最新版本docker部署，在推送设置里点测试可以正常发送消息，但是通过get访问url提示无效的渠道名称
 {"message":"无效的渠道名称：corp_app","success":false}

**Comment by shobalpeng** [comment]
> 

刚刚尝试了一下，消息通道的名称不能自定义，比如用企业微信应用的话，需要把消息通道的名称改成corp_app，我一开始是自己设了个名字，后面改成channel的名字就可以了

**Comment by songquanpeng** [comment]
今天刚刚大版本更新，有些不兼容的改动，文档已更新。

现在 `channel` 字段填的是用户自己设定的渠道名称，而非通道类型。
