### ISSUE TITLE
服务器搭建是无法是使用数据库

### ISSUE THREAD

**Issue by zhengwenxiao** [songquanpeng/message-pusher#7]
data.db 无法放，造成无法登陆

**Comment by songquanpeng** [comment]
用的是 Sequelize ORM，要使用其他数据库的话也很方便进行适配，不过我还没测试过。

请问是为什么没办法放 data.db？可以使用 HEROKU 模式，使用环境变量进行配置。

**Comment by zhengwenxiao** [comment]
data.db  无法访问 ，输入有误

**Comment by songquanpeng** [comment]
输入有误是指用户名密码输入有误？创建数据库时如果发现里面没有用户会自动创建一个管理员用户： `admin` 和 `123456`。

**Comment by songquanpeng** [comment]
另外数据库是不需要管的，会自动创建，这也是为什么要用嵌入式数据库的原因，无需额外配置。

**Comment by zhengwenxiao** [comment]
感觉是没有创建 data.db 文件

**Comment by songquanpeng** [comment]
不应该啊，请问具体的环境是？

**Comment by zhengwenxiao** [comment]
在 message-pusher 文件夹下面并未搜到 对应的  data.db 文件 ；登陆时 输入admin/123456  没有反应 最后会报504；
使用的Ubuntu 20.04；搭配宝塔面板

**Comment by zhengwenxiao** [comment]
nodejs v14.16.0

**Comment by songquanpeng** [comment]
请问是用宝塔装的吗？这我倒是没有试过。

**Comment by zhengwenxiao** [comment]
是的 在宝塔安装的

**Comment by songquanpeng** [comment]
建议直接在命令行使用 pm2 启动服务，详见 README，宝塔我没用过不是很清楚。

**Comment by songquanpeng** [comment]
感谢反馈，这个之后有时间的话我会去做适配。

**Comment by zhengwenxiao** [comment]
我先测试一下，看看是否可行

**Comment by zhengwenxiao** [comment]
session_secret: 'change this',
  cookie_secret: 'change this',
这两个参数不需要调整是吧

**Comment by songquanpeng** [comment]
随便改个值就好，生成 cookie 时要用的，不改也没关系。

**Comment by zhengwenxiao** [comment]
使用 ： npm install --unsafe-perm 解决问题
