### ISSUE TITLE
请求支持 WxPusher

### ISSUE THREAD

**Issue by sunnywangzi** [songquanpeng/message-pusher#72]
如题
官网  http://wxpusher.zjiecode.com

**Comment by songquanpeng** [comment]
感觉套娃了，因为 Message Pusher 和 WxPusher 本质上是一类应用。

**Comment by songquanpeng** [comment]
之后会加一个自定义通道，以支持第三方推送平台。

**Comment by sunnywangzi** [comment]
我主要用他们的微信推送，他们对推送数量的没什么限制，还能显示在微信的首页
