### ISSUE TITLE
微信测试号推送模板优化

### ISSUE THREAD

**Issue by 1275788667** [songquanpeng/message-pusher#74]
推送后需要点击详情才能看到消息 是否可以优化直接显示  不然太不友好了
![微信图片_20230508180153](https://user-images.githubusercontent.com/58962460/236796840-7c51b097-94e9-4814-b9ce-aa803353af30.jpg)

**Comment by songquanpeng** [comment]
测试号只能推送模板消息，之后可以优化一下默认消息模板。



---Original---
From: ***@***.***&gt;
Sent at: 2023年5月8日(Mon) Evening6:05
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/message-pusher] 微信测试号推送优化 (Issue #74)




 
推送后需要点击详情才能看到消息 是否可以优化直接显示  不然太不友好了

**Comment by 1275788667** [comment]
我看了下微信说明 模板消息是可以展示在外而不用点击进去详情看的  包括我上边图上的显示倒数第二条带有测试的  也是模板消息  https://mp.weixin.qq.com/debug/cgi-bin/readtmpl?t=tmplmsg/faq_tmpl

**Comment by songquanpeng** [comment]
我优化一下模板就好了。

**Comment by songquanpeng** [comment]
已支持，已推送版本 `v0.4.3-alpha.1`。

效果：
![62867996a2e494fb64f96bd006c2b41](https://user-images.githubusercontent.com/39998050/236807313-7a7bc89f-a7ba-473f-bc82-688a557f08ef.jpg)
