### ISSUE TITLE
Telegram 推送的消息太长导致：Bad Request: message is too long

### ISSUE THREAD

**Issue by sunnywangzi** [songquanpeng/message-pusher#79]
如题
希望能够自动分割成多消息

**Comment by songquanpeng** [comment]
这个简单，最近搞一下。

**Comment by songquanpeng** [comment]
涉及到 Markdown 解析的问题，直接粗暴的分割会有问题。

能大概说一下你的情景下消息的格式吗？目前打算是按行进行分割，或者让用户手动插入分割符。

**Comment by songquanpeng** [comment]
自行选择的话要搞配置项，不太好实现。

既然是日志，那就直接切割好了。

**Comment by sunnywangzi** [comment]
![Screenshot_20230512084525](https://github.com/songquanpeng/message-pusher/assets/88769439/80d65d14-1919-453d-8283-268678b55e72)
中文会乱码

**Comment by songquanpeng** [comment]
果然会出现这种问题，直接分割还是不太行。

**Comment by songquanpeng** [comment]
已修复，我本地测试通过，已推送 `v0.4.6-alpha.1`

**Comment by sunnywangzi** [comment]
可以了，但是有个问题，原来可以不分割就可以完整推送的文本，现在也会被拆分

**Comment by songquanpeng** [comment]
不应该啊，我没动那个 `TelegramMaxMessageLength`。

**Comment by sunnywangzi** [comment]
不管了，问题不大

**Comment by sunnywangzi** [comment]
不管了，问题不大

**Comment by songquanpeng** [comment]
长度区别大吗？

**Comment by sunnywangzi** [comment]
40~50个字吧？

**Comment by songquanpeng** [comment]
那这还好，不检查了。
