### ISSUE TITLE
Access Token 可防止未授权者利用本系统向你发送消息，留空则不做该检查

### ISSUE THREAD

**Issue by topdcw** [songquanpeng/message-pusher#8]
![image](https://user-images.githubusercontent.com/15315336/114362645-23a9ac80-9baa-11eb-9c7a-2152a93dc851.png)

这个参数实际并未生效。只要加前缀就可以无限发送，并未校验该token，存在安全问题吧。

**Comment by songquanpeng** [comment]
这个还没实现，我给忘了，本来是可选的。

**Comment by songquanpeng** [comment]
其实前缀也算是 token

**Comment by topdcw** [comment]
嗯嗯
