### ISSUE TITLE
搜索历史消息时 显示信息不全

### ISSUE THREAD

**Issue by sunnywangzi** [songquanpeng/message-pusher#81]
![Screenshot_20230512114635](https://github.com/songquanpeng/message-pusher/assets/88769439/f8a0c12e-20f3-4927-bd43-0bc109a956e3)

**Comment by songquanpeng** [comment]
确实有这个问题，我已经知道是哪个地方有问题了。

**Comment by songquanpeng** [comment]
已修复，已推送 `v04.6`。

感谢反馈。

**Comment by sunnywangzi** [comment]
这么快，厉害
