### ISSUE TITLE
企业微信应用推送在安卓微信无法显示正确字体样式

### ISSUE THREAD

**Issue by WangEdward** [songquanpeng/message-pusher#82]
以下的 `Markdown` 在安卓手机微信中无法被正确渲染（文字可以被显示，但是加粗斜体都没有体现）
```
**这是加粗的文字**

*这是倾斜的文字*

***这是斜体加粗的文字***
```
~不排除~**就**是微信内置浏览器的[问题](https://developers.weixin.qq.com/community/develop/doc/000686a28a00a05646d71125251000)

**Comment by songquanpeng** [comment]
这只能等微信修复了，不好改动 Markdown 的解析结果。

**Comment by WangEdward** [comment]
是的，而且就算改解析结果也没有用，无论是自定义字体还是直接加 style，在手机微信浏览器中都是无法被使用的，它的字体处理比较另类。（5年+ 的问题了，着实离谱，看来微信真也没准备修😂）
