### ISSUE TITLE
宝塔部署教程

### ISSUE THREAD

**Issue by zhanggaoxuan** [songquanpeng/message-pusher#84]
1.建议支持宝塔部署，使与其他环境可以共存。
现在宝塔比较火

**Comment by songquanpeng** [comment]
Okay，找个时间我试一下。

相关 issue：#43

**Comment by advisen** [comment]
宝塔下载PM2，做好映射，就可以直接部署上去了

**Comment by songquanpeng** [comment]
Docker 不是自带监控的吗？应该可以不用 pm2。

**Comment by songquanpeng** [comment]
要在宝塔面板上部署 Docker 镜像，你可以按照以下步骤进行操作：

1. 登录到宝塔面板。如果你还没有安装宝塔面板，请先安装并设置好。

2. 在宝塔面板的首页，找到并点击"软件商店"图标。

3. 在软件商店页面中，搜索并选择"Docker"来安装 Docker 插件。

4. 安装完 Docker 插件后，在宝塔面板的首页，你将看到一个"Docker"图标。点击它进入 Docker 管理页面。

5. 在 Docker 管理页面，你可以创建和管理 Docker 镜像、容器等。点击"创建"按钮来创建一个新的容器。

6. 在创建容器的页面上，你需要填写以下信息：
   - 镜像名称：输入你要使用的 Docker 镜像的名称。
   - 容器名称：给容器起一个名称。
   - 映射端口：如果你想将容器的端口映射到宿主机上的某个端口，可以在这里配置。
   - 映射目录：如果你想将容器内的某个目录映射到宿主机上的某个目录，可以在这里配置。

7. 填写完毕后，点击"创建"按钮来创建容器。

8. 创建完成后，你将在 Docker 管理页面看到新创建的容器。你可以点击容器名称进入容器详情页面，在这里你可以查看容器的状态、日志等信息。

这样，你就可以通过宝塔面板成功部署 Docker 镜像了。请注意，你需要提前在宝塔面板上安装并启动 Docker 插件，以便能够进行 Docker 相关操作。
