### ISSUE TITLE
支持指定多个通道进行推送

### ISSUE THREAD

**Issue by ilay1678** [songquanpeng/message-pusher#86]
像server酱那样
`channel: 动态指定本次推送使用的消息通道，选填。如不指定，则使用网站上的消息通道页面设置的通道。支持最多两个通道，多个通道值用竖线|隔开。比如，同时发送服务号和企业微信应用消息通道，则使用 9|66 。通道对应的值如下：`

**Comment by songquanpeng** [comment]
现在支持 `group` 通道类型，只不过是静态的。

请问有什么静态的多通道推送不能 cover 到场景吗？

**Comment by ilay1678** [comment]
sorry，我在readme没看到有相关描述，还以为没有相关功能呢。

**Comment by songquanpeng** [comment]
有的哈
> 群组消息：可以将多个推送通道组合成一个群组，然后向群组发送消息，可以实现一次性推送到多个渠道的功能
