### ISSUE TITLE
利用腾讯云自定义告警实现免费短信通知

### ISSUE THREAD

**Issue by ilay1678** [songquanpeng/message-pusher#87]
参考 https://blog.craftyun.cn/post/165.html

**Comment by songquanpeng** [comment]
API Explorer：https://console.cloud.tencent.com/api/explorer?Product=monitor&Version=2018-07-24&Action=SendCustomAlarmMsg

调用这个需要账号的 Access Token，但是我没找到给子账号设置什么样的对应的最小权限来调用该 API。

**Comment by ilay1678** [comment]
```
{
    "version": "2.0",
    "statement": [
        {
            "effect": "allow",
            "action": [
                "monitor:SendCustomAlarmMsg"
            ],
            "resource": [
                "*"
            ]
        }
    ]
}
```
这个策略应该可以

**Comment by songquanpeng** [comment]
我调通了，总结一下。
1. 新建用户
2. 自定义创建
3. 可访问资源并接收消息
4. 填写用户信息（填写手机号），选中编程访问
5. 新建自定义策略->按策略生成器创建->JSON：
```json
{
    "version": "2.0",
    "statement": [
        {
            "effect": "allow",
            "action": [
                "monitor:SendCustomAlarmMsg"
            ],
            "resource": [
                "*"
            ]
        }
    ]
}
```
7. 关联用户
8. 回到用户创建流程，直接下一步 & 下一步，保存密钥信息。
9. 手机上收到确认短信，点击验证。
10. [新建用户组](https://console.cloud.tencent.com/cam/groups)，把新用户拉入用户组。
11. [新增消息策略](https://console.cloud.tencent.com/monitor/message )，选择刚刚创建的用户组。

**Comment by songquanpeng** [comment]
已实现，已推送 `v0.4.9-alpha`。

不过现在我测试发现没有收到消息，刚刚是可以的，也没有报错，可能是腾讯云的服务抽风了，明天再试一下。

![image](https://github.com/songquanpeng/message-pusher/assets/39998050/8b1348ee-f56d-4158-bcec-c07a6c313428)

**Comment by songquanpeng** [comment]
是我不小心把渠道删了，程序是没问题的：
![image](https://github.com/songquanpeng/message-pusher/assets/39998050/fa96719b-c95b-433a-8064-1235d35afb68)

**Comment by Ahorace** [comment]
配置参数中的消息策略 ID和区域在哪里获取，未找到位置

**Comment by songquanpeng** [comment]
> 配置参数中的消息策略 ID和区域在哪里获取，未找到位置

消息策略：https://console.cloud.tencent.com/monitor/message

区域的话，https://console.cloud.tencent.com/api/explorer?Product=monitor&Version=2018-07-24&Action=SendCustomAlarmMsg

![image](https://github.com/songquanpeng/message-pusher/assets/39998050/cef641a7-47cd-4855-9016-5d8acebdd2ee)

**Comment by Ahorace** [comment]
现在使用腾讯短息报错，(-503)请求参数有误。
消息如下：
{"message":"(-503)请求参数有误。","success":false}

**Comment by songquanpeng** [comment]
最近一两周会比较忙，需要等忙完才能处理。

**Comment by Think-Me** [comment]
都散了吧！！！客服说这个功能下线了。。。
<img width="812" alt="image" src="https://github.com/songquanpeng/message-pusher/assets/28859254/ce6a1d63-acae-4876-a213-bc5a17c765df">

**Comment by songquanpeng** [comment]
吐了，原来真的是 API 变了，白适配了
