### ISSUE TITLE
请问支持企业服务号吗

### ISSUE THREAD

**Issue by lkeme** [songquanpeng/message-pusher#9]
```
公众号设置

类型: 服务号 类型不可变更
```

**Comment by songquanpeng** [comment]
如果你指的企业服务号是指：
1. 面向所有人的公众号：其 API 应该和测试号中的相同，你可以按照 README 中测试号的教程进行设置，但是我没测试过，因为我没有这种类型的公众号。
2. 企业微信中的应用号：按照 README 中企业号的教程进行设置。

**Comment by songquanpeng** [comment]
如果还有问题或者问题未解决请重开 issue，这里先关了哈。
