### ISSUE TITLE
提示 You need to enable JavaScript to run this app

### ISSUE THREAD

**Issue by advisen** [songquanpeng/message-pusher#90]
部署后，页面打开空白，打开控制台提示You need to enable JavaScript to run this app
![Snipaste_2023-05-17_16-26-17](https://github.com/songquanpeng/message-pusher/assets/40630819/1b8dc23d-c4c2-48a1-b6d3-059193695259)
测试如下解决方案，均没起作用
1、服务器配置jdk 1.8.0
2、浏览器检查java也是开启的
3、测试单个执行的[message-pusher](https://github.com/songquanpeng/message-pusher/releases/download/v0.4.9/message-pusher)文件也不行

**Comment by songquanpeng** [comment]
所以 JavaScript 有没有被禁用呢？

**Comment by songquanpeng** [comment]
Demo 站可以打开吗？https://msgpusher.com/

**Comment by advisen** [comment]
可以的，打开没问题

**Comment by songquanpeng** [comment]
有可能是 Nginx 配置的问题，Docker 打包是没问题的。

**Comment by advisen** [comment]
我没部署ng，直接ip+端口访问的

**Comment by songquanpeng** [comment]
那这就很离谱了，你是自己构建还是下载的 release？

**Comment by advisen** [comment]
是直接git clone的，我再检查下，用Docker 再试试

**Comment by songquanpeng** [comment]
果然，你没有构建前端。

**Comment by advisen** [comment]
。。。。我再看看，感谢

**Comment by songquanpeng** [comment]
确实，README 没写清楚，因为大家一般是用编译好的版本或者 Docker 镜像，我一直没注意到 README 中关于手动部署的部分不全。
