### ISSUE TITLE
复制报错：TypeError: Cannot read properties of undefined (reading 'writeText')

### ISSUE THREAD

**Issue by 1275788667** [songquanpeng/message-pusher#91]
如图 重新部署是一样的问题 采用docker方式部署的
![1684467339174](https://github.com/songquanpeng/message-pusher/assets/58962460/b2f7c862-e993-4e39-ad58-5f0793658fa2)
![1684467323521](https://github.com/songquanpeng/message-pusher/assets/58962460/eb928f0b-f8e7-4997-b146-14f28f03c9a9)

**Comment by songquanpeng** [comment]
这个接口要求 HTTPS。

**Comment by songquanpeng** [comment]
为了功能正常使用，也为了你的消息内容不被窃听，还是推荐使用 Nginx 反代启用 HTTPS。
