### ISSUE TITLE
新增用户key 推送使用key不使用username

### ISSUE THREAD

**Issue by Ubugs** [songquanpeng/message-pusher#92]
建议新增用户key然后根据key进行推送 并提供重置key的功能 避免用户名泄露导致被轰炸

**Comment by songquanpeng** [comment]
可以添加验证 token 的，而且可以选择重置用户名。

**Comment by Ubugs** [comment]
可能我没仔细看 有这个就好👌

**Comment by songquanpeng** [comment]
刚刚我修改了一下代码，现在在 POST 方式下也可以通过 URL 查询参数的方式设置 `token` 字段了。

当然，仍然可以在请求体中进行设置。
