### ISSUE TITLE
如何切换 MySQL？

### ISSUE THREAD

**Issue by advisen** [songquanpeng/message-pusher#93]
按文指导修改SQL_DSN信息
文件路径：/message-pusher/model/main.go
数据库版本：Mysql 5.7.40
修改如下，还是创建并了SQLite文件，请问是否修改错了
`if os.Getenv("SQL_DSN")="push:PiM88DeZHBiR6eBR@tcp(127.0.0.1:3306)/push" {`
![image](https://github.com/songquanpeng/message-pusher/assets/40630819/c86c5118-4675-4f33-b557-db76cdb57c95)
![image](https://github.com/songquanpeng/message-pusher/assets/40630819/8c07d0c9-ad58-4919-ba40-4f28b9fd6104)

**Comment by songquanpeng** [comment]
啊这，不用修改代码的，SQL_DSN 是环境变量。

**Comment by advisen** [comment]
额，那我看错了，那数据库在什么地方修改欸，我在页面上面也没看到可以设置的地方

**Comment by songquanpeng** [comment]
是环境变量哈。

**Comment by songquanpeng** [comment]
在Linux中，可以使用不同的方法来设置环境变量，以便在程序启动时生效。以下是几种常用的方法：

1. 在启动脚本中设置环境变量：可以在程序的启动脚本中直接设置环境变量。例如，在Bash脚本中，可以使用以下语法：
   ```bash
   #!/bin/bash
   export MY_VARIABLE="my_value"
   ./my_program
   ```
   在这个例子中，`MY_VARIABLE`是要设置的环境变量，`my_value`是它的值。通过使用`export`命令，将变量导出为环境变量，然后启动程序。

2. 在命令行中设置环境变量：如果你是在命令行中直接启动程序，可以在启动命令前设置环境变量。例如：
   ```bash
   MY_VARIABLE="my_value" ./my_program
   ```
   这将在启动`my_program`之前设置`MY_VARIABLE`环境变量。

3. 在用户的配置文件中设置环境变量：可以将环境变量添加到用户的配置文件（如`~/.bashrc`或`~/.bash_profile`），这样每次用户登录时都会加载这些变量。你可以编辑适当的配置文件，添加类似于以下行的内容：
   ```bash
   export MY_VARIABLE="my_value"
   ```
   保存文件后，新打开的终端会话或重新登录后，变量将自动设置为环境变量。

对于Docker容器，你可以使用不同的方法在启动镜像时设置环境变量：

1. 使用Docker命令行选项：可以在使用`docker run`命令启动容器时使用`-e`选项设置环境变量。例如：
   ```bash
   docker run -e MY_VARIABLE="my_value" my_image
   ```
   这将在启动名为`my_image`的Docker镜像时，将`MY_VARIABLE`设置为`my_value`。

2. 使用Docker Compose配置文件：如果你使用Docker Compose来定义和管理容器，你可以在Compose文件中设置环境变量。例如：
   ```yaml
   version: '3'
   services:
     my_service:
       image: my_image
       environment:
         - MY_VARIABLE=my_value
   ```
   在这个示例中，`MY_VARIABLE`被设置为`my_value`，并且会传递给名为`my_service`的容器。

这些方法可以根据你的需求选择适合的方式来设置环境变量。

**Comment by advisen** [comment]
了解了，感谢，我以为从代码上面改

**Comment by malsony** [comment]
建议把这些写在一个配置文件里，以后只要：
message-pusher --config-file /etc/message-pusher/config.yml 
就可以了
端口号，是否用MySQL/MariaDB，日志文档目录等等都怼上去
