### ISSUE TITLE
想发送这种消息怎么设置呀

### ISSUE THREAD

**Issue by lovefan-fan** [songquanpeng/message-pusher#94]
![image](https://github.com/songquanpeng/message-pusher/assets/76868069/0cb5eabf-6844-45c9-9b65-214803c3c527)

**Comment by songquanpeng** [comment]
这是什么平台？

**Comment by lovefan-fan** [comment]
> 这是什么平台？

微信测试号呀

**Comment by songquanpeng** [comment]
这个估计是自定义的消息模板。

**Comment by lovefan-fan** [comment]
> 这个估计是自定义的消息模板。

哦哦，咱们还不支持是吧

**Comment by songquanpeng** [comment]
支持自定义消息模板的。

**Comment by songquanpeng** [comment]
你写消息模板的时候注意使用指定的字段即可。

**Comment by songquanpeng** [comment]
稍后我加一个日期变量。

![image](https://github.com/songquanpeng/message-pusher/assets/39998050/04fc6db3-e984-40a1-abac-3dc1ed61e5c9)

**Comment by lovefan-fan** [comment]
> 

![image](https://github.com/songquanpeng/message-pusher/assets/76868069/ef99ecba-b787-4986-a4ca-a4d9c1ac78c9)
请问一下我是不是哪里没弄对呀

**Comment by songquanpeng** [comment]
模板内容 text.DATA 改成 description.DATA 试一下。

**Comment by lovefan-fan** [comment]
> 

还是一样，我应该是哪里没设置对，模板内容不管是啥，我请求的时候传title，description什么的都能生效

**Comment by songquanpeng** [comment]
模板 ID 更新了吗？

**Comment by lovefan-fan** [comment]
> 模板 ID 更新了吗？

更新了的

**Comment by lovefan-fan** [comment]
和微信测试公众号平台的接口配置信息项有关吗，我一直提交都是配置失败

**Comment by songquanpeng** [comment]
那个对于 Message Pusher 来说没用。

**Comment by songquanpeng** [comment]
我测试了一下，貌似不让只填一个 {{description.DATA}}，前面加个“描述：”就可以了。

**Comment by lovefan-fan** [comment]
> 

感谢，成功了，虽然效果不一样，但是也能一目了然

**Comment by songquanpeng** [comment]
这个我猜是微信的限制，之前这个模板是不需要加前缀就能用的。
